### ISSUE TITLE
Stuck on Waiting for Data when using Next.js

### ISSUE THREAD

**Issue by rleija703** [ReactVT/react-vt#72]
I'm currently testing it with Next.js and it won't work. It gets stuck at the _Waiting for data_ loading screen. Code is very generic.

```
import React, { Component } from 'react';
import reactVT from 'react-vt';

export default class Test extends Component {

  componentWillUpdate() {
    reactVT( React, this )
  }

  render() {
    return (
      <h1>Helo</h1>
    )
  }
}
```

**Comment by rleija703** [comment]
I just realized that I wasn't on the top level component. I went into the next node module and edited the `next/dist/lib/app.js` file in the module. I added the component lifecycle _componentWillMount_ and added the following code the App object.

```
{
    key: 'componentWillMount',
    value: function componentWillMount() {
      if ( typeof window !== 'undefined' ) {
        console.log(this, 'adding react vt')
        reactVT(_react, this)
      }
    }
  }
```

Still I face the problem with **Waiting for Data**

**Comment by icrustandi** [comment]
Thanks for reporting this. Unfortunately React VT doesn't currently support Next.js. We'll work on adding more helpful error handling in the meantime. We've also added a note in our documentation for those who are looking into getting this to work with Next.js.
