### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by leomoreno** [ReactVT/react-vt#75]
I tried to use react-vt with my [Grommet](https://github.com/grommet/grommet) based project and no success.

[This line](https://github.com/ReactVT/react-vt/blob/a64bfcb2763f468b24a37d39b4f8a572407175d2/src/inject.js#L52) is throwing the DOMException.

Any thoughts about how to address it?

<img width="1100" alt="reac-vt" src="https://user-images.githubusercontent.com/1276390/29732395-0ce8b930-89ae-11e7-8fea-7c46527e22b0.png">

**Comment by icrustandi** [comment]
Is this a public project that we can take a look at? We're unfamiliar with the way Grommet interacts with the rest of a React application - does it modify the browser context or the way React creates nodes in any way? 

Could you also let us know what version of React that you're on and whether or not you're using redux/react-redux or react-router?

**Comment by leomoreno** [comment]
Not a public project sorry. I can't tell if Grommet does something like what you are mentioning.

The versions I'm using:
- React: ^15.4.0
- React-router-dom: ^4.0.0
- React-redux: ^4.4.5
- Redux: ^3.6.0

**Comment by Gryff** [comment]
Trying with a private project I get the error `ReferenceError: window is not defined`. This could be the same in your case? 

Does react-vt not play well with components accessing the global window object?

**Comment by icrustandi** [comment]
@leomoreno since you're using react-router - please see issue [76](https://github.com/ReactVT/react-vt/issues/76)

@Gryff react-vt uses window.postMessage and listeners to send the DOM information from the React app to the chrome devTools extension (and vice versa). Could there be something in your application that might be preventing it from doing that?

**Comment by leomoreno** [comment]
I'm not sure if that's the case @icrustandi. Any way Grommet uses RR. So I until it's supported I think further debug it doesn't make sense.

**Comment by Gryff** [comment]
@icrustandi I think I see the problem with my app then - it is rendered server side first.

**Comment by icrustandi** [comment]
@Gryff Assuming that your app isn't using react router - could you try inserting the 'reactVT(React, this)' line in componentDidMount instead of WillMount? Code in componentDidMount should only run client-side, so this should get rid of the reference error.

**Comment by Gryff** [comment]
Thanks @icrustandi, I'm getting closer :) 
Now I'm only seeing one component in the tree, the top level component.
Reading through your comment on #76 I `console.log`'d the `_reactInternalInstance` of the component and checked the structure compared to the code in `dom-parse.js`. It seems that traversing through children on line 125 looks for `dom._reactInternalInstance._renderedComponent._renderedChildren`, when I look at my top level component's instance the `_renderedChildren` doesn't exist. However it does exist one layer down in `dom._reactInternalInstance._renderedComponent._renderedComponent._renderedChildren`. 
Not sure if this helps.

**Comment by icrustandi** [comment]
@Gryff Interesting - what do you see on dom._reactInternalInstance._renderedComponent._renderedComponent._renderedChildren? If they're actual nodes of children components, then that might be what we're looking for - you can manually change line 125 to reflect it, and a separate logic for traversing the children should take care of the rest. 

How do you have your parent component structured  - or better yet, how do you have your component tree structured? Also, what version of React are you running for your dependency? We've only seen ._renderedComponent nesting when we introduced react router into an application - so I wonder what other dependencies you might have for your project.

**Comment by Gryff** [comment]
Ok, I edited line 125 as suggested. This threw a few errors to do with `_renderedComponent.hostNode` being undefined when trying to get id and className. So I put it `_renderedComponent.hostNode && ...` and I have a tree! 👍 
However, not all nodes are named. Some are named after my react classes, some are html tags, others are blank.

In terms of the app structure - not sure what details you're looking for. It's quite a big app. There's a mix of es6 classes extending `React.Component`, others using `React.createClass`, others are just functions. There's a mix of `import ... from '...'` and `const ... = require('...')`, which means there's also a mix of `export default` and `module.exports`.

Dependencies for the project
react and react-dom v15.6.1. 
prop-types v15.5.10
No redux.
No react router.
Some private react component packages.
babel-preset-es2015: v6.24.1
babel-preset-react: v6.24.1
babel-plugin-transform-object-assign: v6.22.0
babel-plugin-transform-runtime: v6.23.0
babel-plugin-transform-strict-mode: v6.24.1
babel-polyfill: v6.26.0

Does this help?
